### ISSUE TITLE
Make the rootless container feature, optional

### ISSUE THREAD

**Issue by petersem** [enchant97/hasty-paste#72]
It is a pain to be forced down the rootless path, when it was all working fine as is. I would much prefer to keep backwards compatibility, and only have rootless as an extra option, or not at all. 

Maybe have an option to supply an environmental var for the puid/pgid for it to run as, rather than hard code to nobody?

**Comment by enchant97** [comment]
Starting with version 1.8 the default user will be `nobody`, this ensures new users will always have Hasty Paste run with least privileges.

It does not need the Docker daemon to be rootless, this change just effects the running container. Therefore will run in both rooted Docker (default install) and Rootless installs.

## Existing Users
### Run With Defaults
For existing users, who have been running the image using the root account, the only change that is required is to change the ownership of the app data.

If using Docker volumes this command can be run to find where the volume data is located:

```
docker volume inspect <volume name>
```

Then change the ownership:

```
chown -R nobody:nobody <volume path>/_data/
```

### Override Defaults
You can always override the default user set in the image to get back to before V1.8; by using the following:

> Depending on your system 0:0 may need to be provided instead of root:root

```
docker run ... --user root:root
```

Or in Docker Compose:

```yml
version: "3"

services:
  paste-bin:
    user: root:root
```

**Comment by modem7** [comment]
There might be an easy way to resolve this that will appease all parties (I'm one of those who don't overly like changing my bind mount permissions to things other than what I have set with my personal security measures). 

Set the user at the entrypoint script level. 

E.g. a variable such as:

```bash
HASTEUSER=${HASTEUSER:-nobody:nobody}
```

Set the relevant permissions at the entrypoint level.

This is obviously not a fully thought out idea, and would need mulling over.

---

Both myself and @petersem would be happy to investigate on our end, and verify that processes inside the container do not run as root with whichever solution we offer. 

At that point, @enchant97 can see if this is a suitable solution from their viewpoint, and we can go on from there. Does this seem like an amenable solution?

**Comment by petersem** [comment]
@modem7 good plan. Like you, I don't want to screw around with my bind mount permissions. There has to be an easier way. 👍

**Comment by enchant97** [comment]
Running the container as root then launching the app using a defined puid:pgid would work, however the container main process still runs as root, _unless using docker rootless_.

I see the best solution as overriding the default user through the docker --user command. I wouldn't consider it a hack since it is a feature of Docker and ensures the main container process including any other processes get launched with that set user, which is not guaranteed when just setting the app to launch as a different user (after container construction).

I would like demonstrate that the solution you suggested compared to mine, requires a similar line being added to the config (meaning neither solution is harder to implement than the other):

```yml
version: "3"

services:
  paste-bin:
    # overriding the user through Docker
    user: puid:pgid
    # override using an env variable
    environment:
      - "HASTEUSER=puid:pgid"
```

I am happy to investigate further to see if using the environment variable approach could potentially work, however I have tested before and main container process stayed as root whilst the app was run with the selected user.

**Comment by modem7** [comment]
We can get past the main process running as root by calling the process via exec, which would replace the process as PID1.

Obviously, this would require testing to make sure everything is on the up n up.
